name: Feature Report
description: File a feature report
title: "[FEAT]: "
labels: ["enhancement"]
assignees:
  - dmike16
body:
  - type: markdown
    attributes:
      value: |
        (\U0001F680) Great, i have an idea!
  - type: textarea
    id: solution
    attributes:
      label: Your solution
      description: Please describe the desired behavior
      placeholder: Describe the solution you'd like!
      value: "We can do..!"
    validations:
      required: true
  - type: textarea
    id: other-solution
    attributes:
      label: Your alternative solution
      description: Please describe the alternative behavior
      placeholder: Describe the alternative solution you'd like!
      value: "Or we can do..!"
    validations:
      required: false
  - type: checkboxes
    id: source
    attributes:
      label: Source of feature
      description: Is your feature request related to a problem?
      options:
        - label: "Yes"
          required: true
